# .github/workflows/release.yml
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM dependencies
        run: npm install

      - name: Setup system dependencies
        run: bash.exe ./setup.sh x64

      - name: Build
        run: bash.exe ./build.sh x64

      - run: ls lib/build/
