# .github/workflows/release.yml
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: seanmiddleditch/gha-setup-vsdevenv@master

      - name: Setup system dependencies
        run: C:\msys64\usr\bin\bash.exe ./setup.sh x64

      - name: Build
        run: C:\msys64\usr\bin\bash.exe ./build.sh x64

      - run: ls lib/build/
